apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-api.fullname" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "platform-api.name" . }}
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from workloads in the platform namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: platform
      ports:
        - protocol: TCP
          port: 8080

    # Allow traffic from the NGINX Ingress Controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
