{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-api.fullname" . }}-secret
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_NAME: {{ .Values.secret.appName | quote }}
  APP_MODE: {{ .Values.secret.appMode | quote }}
{{- end }}
