apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api.fullname" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "platform-api.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
